import Head from "next/head";
import { Inter } from "@next/font/google";
import { readPostsByCategories } from "@/api";
import WrapperComponent from "@/components/WrapperComponent";
import RecentPosts from "@/components/RecentPosts";

const inter = Inter({ subsets: ["latin"] });

export const getStaticProps = async () => {
  return { props: { postsForAllCategories: readPostsByCategories() } };
};

const Home = ({ postsForAllCategories }) => {
  return (
    <>
      <Head>
        <title>anuran-Chakraborty.github.io</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapperComponent>
        <main>
          <RecentPosts postsForAllCategories={postsForAllCategories} />
        </main>
      </WrapperComponent>
    </>
  );
};

export default Home;
