import Head from "next/head";
import { Inter } from "@next/font/google";
import { readPostsByCategories } from "@/api";

const inter = Inter({ subsets: ["latin"] });

export const getStaticProps = async () => {
  return { props: { postsForAllCategories: readPostsByCategories() } };
};

const Home = ({ postsForAllCategories }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello</h1>
      </main>
    </>
  );
};

export default Home;
